### ISSUE TITLE
Fix fastlane beta ios

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#1081]
There has been a question if we can deploy reactNativeApp to testflight. Fastlane should be correctly set up for this task, however it fails on codesigning for the two new build targets (framework and native playground).

**Comment by mrtnzlml** [comment]
> There has been a question if we can deploy reactNativeApp to testflight.

FYI - they already have Android build so they can see it. Therefore, it's not ASAP anymore but it would be nice to have it there for sure... :)

**Comment by lukewalczak** [comment]
It is working again 🎉 the issue probably was an expired certificate. 

I see some improvements for the future:

* pushing the app to the tesflight on every merge to master
* notify users on slack that new version is released

Feel free to open the new issue in the future if you will decide it makes sense.
