### ISSUE TITLE
Embedding RN screen in Android fragment

### ISSUE THREAD

**Issue by Blackhex** [kiwicom/mobile#1093]
If there will be a requirement to put RN screen/feature inside a tab navigation page on Android in the future it would be needed to render that screen inside a Fragment. Therefore it is needed to investigate whether this is technically possible with the current RN architecture and if yes provide some demo of this concept.

**Comment by ferrannp** [comment]
Yeah I remember that library when it came out. I think it worked pretty ok (small code). What you are asking should be possible. We could provide the demo inside our playground app.

**Comment by Blackhex** [comment]
Great, thanks.
