### ISSUE TITLE
Inquire/Replace react-native-share with React Native built-in library

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/mobile#1112]
On https://github.com/react-native-community/react-native-share, they say:

NOTE: React Native now implements share functionality [Read more](https://facebook.github.io/react-native/docs/share.html)

which points to this React Native documentation page: https://facebook.github.io/react-native/docs/share.html

**Comment by ferrannp** [comment]
Looks good to me, the less native libraries the better.

**Comment by lukewalczak** [comment]
Due to [`Share`](https://github.com/react-native-community/react-native-share) module from RN doesnt support `url` on android, it's pointless to change only iOS part. Closing with the hope that RN will support it like `react-native-share` does it.
