### ISSUE TITLE
[IMPROVEMENT] DropMarker component

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/mobile#1225]
The existing component does not look exactly like the design.
Besides there are some artefacts like `size` props from before; there should still be a way to make the `DropMarker` bigger.

**Comment by tbergq** [comment]
@RobinCsl, you mentioned we could get it as a `png` any news on this?

**Comment by RobinCsl** [comment]
I had started on this and somehow forgot about it. I could take care of it today if you would like.

**Comment by tbergq** [comment]
No rush, do it when you have time
