### ISSUE TITLE
Room is not selected on tablet when navigation to booking payment screen

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#1269]

**Comment by RobinCsl** [comment]
@tbergq we can close this now, false alarm.

**Comment by tbergq** [comment]
> we can close this now, false alarm.

Please elaborate?

**Comment by RobinCsl** [comment]
Well this was due to your PR about the `id` replacing the `originalId`, and the selecting of 2 rooms for 1 guest.
