### ISSUE TITLE
[Hotels] Orientation for mobile, possible to change from portrait to lanscape

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#1380]
For iOS, this is deactivated by the native app itself, and I supposed it was the same for android. But maybe it is not?

Could you investigate, and fix if there is something we need to do?

**Comment by ferrannp** [comment]
If you want to have only portrait, the Android activity that uses `rnkiwmobile` can just set up this:

```kt
requestedOrientation = ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
```

Like we do in our playground https://github.com/kiwicom/mobile/blob/master/android/playground/src/main/java/com/kiwi/mobile/rnandroidplayground/HotelsActivity.kt#L16.
