### ISSUE TITLE
GraphQL: please stop using "databaseID"

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/mobile#1404]
Or any other deprecated field. See: https://github.com/kiwicom/mobile/search?q=%22databaseId%22&unscoped_q=%22databaseId%22

You can use `id(opaque: false)` if you really need it. Please let me know if something is difficult to do. One little trick could help you significantly - write queries like this:

```graphql
{
  faq {
    databaseId: id(opaque: false)
  }
}
```

You can refactor later but the important thing is you stop using deprecated fields and therefore we can move forward in graphql.kiwi.com. Thanks!

**Comment by tbergq** [comment]
These are all used in MMB, I consider MMB in RN to be dead. Please feel free to remove those fields from graphql. 

If MMB-RN is ever revived, I expect there will be a lot to fix.
