### ISSUE TITLE
Inquire why "@kiwicom/react-native-app-hotels" is a dependency for MMB

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/mobile#1406]
Adopting @kiwicom/eslint-config, we had to add `"@kiwicom/react-native-app-hotels":"^0",` as a dependency to MMB.

If we go back to MMB, we will need to inquire why.

https://github.com/kiwicom/mobile/pull/1405#discussion_r245907920

**Comment by RobinCsl** [comment]
https://github.com/kiwicom/mobile/pull/1405#discussion_r246039384

That means we'll need to make sure versions are properly compatible with one another.

**Comment by ferrannp** [comment]
I think it definitely should not be. @tbergq ?

**Comment by tbergq** [comment]
It definitely should be. From tripservices in MMB you can open hotels.
