### ISSUE TITLE
Use decimal.js for new money type

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#1541]

**Comment by tbergq** [comment]
![screen](https://user-images.githubusercontent.com/7705041/55321643-7f4ce580-547a-11e9-8ce0-44de0f8fe973.png)

**Comment by mrtnzlml** [comment]
@tbergq Tip - I used this lighter version instead: https://github.com/MikeMcl/decimal.js-light/ (it's the same but without some less needed features)

**Comment by tbergq** [comment]
Thanks for pointing it out, I made a new issue to investigate it #1546
