### ISSUE TITLE
Use `decimal.js` or `dinero.js` to deal with money

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/mobile#1542]
Use `decimal.js` or `dinero.js` to deal with money

When computing money amounts, JS is not very precise, and can lead to unwanted UI renders:
![screen](https://user-images.githubusercontent.com/22741774/55321713-a2779500-547a-11e9-9261-7a51c5ef5c63.png)

**Comment by tbergq** [comment]
duplicate of #1541
