### ISSUE TITLE
Evaluate necessity to disable `prefer-named-capture-group`

### ISSUE THREAD

**Issue by RobinCsl** [kiwicom/mobile#1665]
This causes runtime errors on iOS < 12:
```
Fatal Exception: RCTFatalException: Unhandled JS Exception: Invalid regular expression: unrecognized character after (?
```
So we might fall into this category:
https://eslint.org/docs/rules/prefer-named-capture-group#when-not-to-use-it

Files to check should be:
- [ ] https://github.com/kiwicom/mobile/blob/master/packages/shared/src/Color.js
- [ ] https://github.com/kiwicom/mobile/blob/master/packages/localization/src/TranslationHelpers.js

**Comment by tbergq** [comment]
We might just need to add some babel-plugin.

**Comment by RobinCsl** [comment]
Or that :-)
