### ISSUE TITLE
Fix broken react-library.gradle

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#1673]
This file was created on 31st October 2018, it seems to be a copy paste of [react.gradle](https://github.com/facebook/react-native/blob/master/react.gradle) with maybe some tiny modifications. 

The original file has changed a lot, and this is not reflected in our [react-library.gradle](https://github.com/kiwicom/mobile/blob/master/android/rnkiwimobile/react-library.gradle)

One should be able to fix it mostly by comparing the changelog of the file from react-native and apply to ours. Note that we have had some changes to this file as well since it was created.

**Comment by tbergq** [comment]
The most important thing is that hermes does not work when our `rnkiwimobile` framework is released. This needs to be fixed.

**Comment by Blackhex** [comment]
MR #1676 fixes the Hermes loading problem but does not update the rect-library.gradle.

**Comment by tbergq** [comment]
Seems this is working for now. Closing
