### ISSUE TITLE
Biggest pains

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/mobile#466]
## Navigation ❓ 
Our navigation (from JS point of view) is not very developer friendly. It's also complicated because of native team requirements.

Solution: We should wrap the navigation into our own custom wrapper. This will solve the developer friendliness.

## Redux ✅ 
~Redux is hard. In our case, it's also a very big mess. The question is: do we need Redux?~

~Solution: There is new React Context and our state management is not so complicated. Let's try only this and we can, later on, try [Unstated](https://github.com/jamiebuilds/unstated) for example.~

Redux has been completely replaced by React Context. It's still painful because of our internal store structure. However, there are two significant improvements:

- we do not have one huge state store but separated contexts
- we do not use string action names anymore but functions from the context

## Map ❓
There is a lot of bugs on our map. They could be mostly avoided by better design but I would like to replace them with beautiful [Mapbox](https://www.mapbox.com/). Oh and yes - there is Mapbox on Kiwi.com frontend as well.

## Sync/async native code vs. debugging ✅ 
~We currently use sync native methods but there is one big disadvantage: we cannot use freely our debug tools.~

We now use only async methods. See below...

## Playground needs improvements 👨‍💻 
I still think that Playground is a great concept but it's not super DX friendly. We should work on it.

## Async `AdaptableLayout` workaround 👨‍💻
We are currently workarounding RN limitation because of iOS multitasking. Would be great to have a better solution (read not a workaround). See: https://github.com/facebook/react-native/issues/16152

**Comment by tbergq** [comment]
> ## Sync/async native code vs. debugging
We currently use sync native methods but there is one big disadvantage: we cannot use freely our debug tools.

Possible solution: 
Translations, change native code to use promise, then translation component could do
``` 
componentDidMount = async () => {
  const key = this.props.id;
  const nativeKey = 'mobile.' + key;
  const translatedString =  await NativeModules.RNTranslationManager.translate(
    nativeKey,
  );
  this.setState({ translatedString })
}

render = () => (
  <Text style={containerStyle}>
    {CaseTransform(
      this.replaceValues(this.state.translatedString, values),
      this.props.textTransform,
    )}
  </Text>
)
```
Possible problem, this will cause component to render, then re-render when set state is called. We need to verify that the user does not notice this. 

The other method is CurrencyFormatter, we should do some similar wrapping there.

**Comment by mrtnzlml** [comment]
@tbergq I was thinking about exactly the same. I would like to try it. We can try to render empty string and later replace it with the translation result...

**Comment by tbergq** [comment]
Yes, I am on it now, I am adding a method `translateAsync` and testing it locally, so far, it seems very good.

**Comment by tbergq** [comment]
## AllHotelsQuery

We have two possible ways to query hotels. cityId and coordinates. 
This leads to this ternary in `AllHotels`

```
{this.props.cityId ? (
            <AllHotelsSearch
              coordinates={this.props.coordinates}
              openSingleHotel={this.props.openSingleHotel}
              cityId={this.props.cityId}
              currency={this.props.currency}
              setCurrentCityName={this.setCurrentCityName}
            />
          ) : (
            <PublicApiRenderer
              query={graphql`
                query AllHotels_cityLookup_Query($prefix: String!) {
                  city: hotelCities(prefix: $prefix, first: 1) {
                    edges {
                      node {
                        id
                      }
                    }
                  }
                }
              `}
              render={this.renderAllHotelsSearchPublicRenderer}
              variables={{
                prefix: this.props.location,
              }}
            />
          )}
```

Further down the line we have this logic to determine to use coordinates or location:
```
if (hasCoordinates(coordinates) && location === '') {
    params.latitude = idx(coordinates, _ => _.latitude);
    params.longitude = idx(coordinates, _ => _.longitude);
  } else if (cityId) {
    params.cityId = cityId;
  }
```

It is getting difficult to handle, and difficult to understand.

Solution: Refactor this logic and these components. Find a better way to do it.
