### ISSUE TITLE
Tablet layout

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#520]
Tablet has basically two screens
- [x] MMBList
- [ ] Landing-Details

Landing details is fixed to the left side, and when you interact with the buttons, you render its content to the right side of the tablet. 

## Questions
- Design shows how it looks like in landscape mode, how should it look like in portrait mode?

**Comment by mrtnzlml** [comment]
The Android design is missing. At least screenshots would be great but it's not gonna be pixel perfect (I don't know how to design the menu)...

**Comment by mrtnzlml** [comment]
Also - there are green arrows on mobile but no arrows on the tablet (in the menu). Is it correct or just another design flaw?

**Comment by mrtnzlml** [comment]
> Ragarding the portrait mode: the width of the left column should be static (same for both landscape and portrait). The width of the the right column is dynamic in the portrait mode.

Are you sure about that? Should it always be 520pt in the portrait mode? I am just following the instructions but it really doesn't work very well. That's why we asked in the first place (because we already implemented this and it's truly horrible)... 😢 

> there is no design for it of course

Of course... 😀

**Comment by MRTNKCR** [comment]
> Are you sure about that? Should it always be 520pt in the portrait mode? I am just following the instructions but it really doesn't work very well. That's why we asked in the first place (because we already implemented this and it's truly horrible)... 😢

I will ask again. Can you maybe share a screenshot of what you got? I will compare it with the design and ask @vousatej for further instructions.

Here are the screens from Android: https://drive.google.com/drive/folders/1UnW31KjxblIeoyzR1prFdc4wrsOAASqv

**Comment by mrtnzlml** [comment]
![simulator screen shot - ipad pro 10 5-inch - 2018-05-09 at 15 39 05](https://user-images.githubusercontent.com/978368/39818014-229e700a-53a0-11e8-8f50-eb513e3a4393.png)

**Comment by mrtnzlml** [comment]
![simulator screen shot - ipad pro 10 5-inch - 2018-05-09 at 15 39 05](https://user-images.githubusercontent.com/978368/39818208-a9361c08-53a0-11e8-86d9-efee62a245f0.png)
