### ISSUE TITLE
Trip services screen

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#521]
[Zeplin](https://zpl.io/bezpZNP)

## Tasks
- [ ] Pull to refresh

## Questions
- Basically all buttons in this screen opens a webview. What are the urls to these views?
- Icons?
- When should this modal open?
![skjermbilde 2018-05-03 kl 15 06 40](https://user-images.githubusercontent.com/7705041/39578133-a0295312-4ee3-11e8-9a73-f882926d15da.png)

## Other
- We need native to provide a way for us to navigate to hotels (when we click on `Hotel` button)

**Comment by mrtnzlml** [comment]
> We need native to provide a way for us to navigate to hotels (when we click on Hotel button)

It's part of our application so we can use our independent hotel component inside this MMB module, right?

**Comment by tbergq** [comment]
1) insurance update
```
https://booking-api.skypicker.com/api/v0.1/users/self/bookings/BID?token=token
{
    "action": "create"
    "category": "update_insurances",
    "currency": <CURRENCY_CODE>,
    "data": {
        [
            "pid": <PASSENGER_ID>,
            "insurance": <NEW_INSURANCE_TYPE>
        ]        
    },
    "orig_price": <PRICE>,
    "payment": {
        "gate": "zooz"
    },
    "use_credits": <true/false>,
    "booked_at": <AFFIL_ID>
}
```

2) pay, get payment token —> SDK (PaymentOS) - spec here: https://confluence.kiwi.com/display/MOB/PaymentOS+specification

3) payment confirmation:
```
https://booking-api.skypicker.com/api/v0.1/users/self/bookings/BID?token=token
{
    "action": "finishPayment"
    "category": "update_insurances",
    "abid": <ABID>,
    "payment": {
        "method_token": <TOKEN_FROM_PAYMENT>
    }
}
```

**Comment by mrtnzlml** [comment]
🎉
