### ISSUE TITLE
Call support screen

### ISSUE THREAD

**Issue by tbergquist-godaddy** [kiwicom/mobile#524]
[Zeplin](https://zpl.io/V1ZEWwB)
![image](https://cdn.zeplin.io/59a9818fe86dfd4f75f2c142/screens/CF2E5D6C-7F85-47EE-BBF8-DE7FF9D92F76.png)

## Questions
- Where do we get the opening hours for each country, phone numbers etc.
- Icons?

**Comment by MRTNKCR** [comment]
These contacts are hardcoded, here is a link to the FE repo: https://gitlab.skypicker.com/frontend/hankey

The icons should be pulled from Fontastic.

**Comment by mrtnzlml** [comment]
@MRTNKCR So are they hardcoded or are they in the Hankey API? This is not very helpful... 😞 I read brefly the Hankey code and seems like it deals only with currencies, countries, and languages.

**Comment by MRTNKCR** [comment]
@oreqizer please, could you help us with this one? ⬆️

**Comment by oreqizer** [comment]
Ain't it from the brand config?

**Comment by mrtnzlml** [comment]
Right. 😸 What is brand config? Seems like there is an API for it anyway so we should probably wait for help from someone who is working on it.

**Comment by mrtnzlml** [comment]
@MRTNKCR Where are the icons actually? You were quickly done here, but these are not icons from the Fontastic...

**Comment by MRTNKCR** [comment]
The only other option is Material repo, according to Vousatej, Fontastic is the preferred source, everything missing should be pulled from Material https://material.io/tools/icons/

**Comment by mrtnzlml** [comment]
These are not icons from Fontastic nor from Material design. 😞

**Comment by MRTNKCR** [comment]
Oh, you mean those flags..?

**Comment by mrtnzlml** [comment]
See: https://github.com/kiwicom/mobile/issues/524
