### ISSUE TITLE
Others page

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#526]
[Zeplin](https://zpl.io/2jZrwDQ)
![image](https://cdn.zeplin.io/59a9818fe86dfd4f75f2c142/screens/9F928EDD-22CB-43E6-9B15-814A958C8BEF.png)

## Questions
- webview urls?

**Comment by MRTNKCR** [comment]
Here is a list of deeplinks from the app, Invoice + Open on the web are missing, @janka.mertinakova promised to add them https://paper.dropbox.com/doc/MMB-Deeplinks-NxiT0ZiaZP1sl7qibRcMg

**Comment by tbergq** [comment]
@mrtnzlml have a look at this
https://medium.com/react-native-training/deep-linking-your-react-native-app-d87c39a1ad5e

though that by itself is not enough, a deeplink should be something like `peopleapp://people/0` and we don't know anymore that the query paramater from that document

@MRTNKCR could you please find the base deeplink url for us?

**Comment by mrtnzlml** [comment]
@tbergq From what I understand this is already "deep link" to the web app (MMB to be more specific). The prefix is, therefore `https://...`. But I was not able to open it with my BID. I got almost there but it was not possible to log in. And it must work differently in mobile webview of course...

**Comment by tbergq** [comment]
@MRTNKCR please help us with ^^

**Comment by MRTNKCR** [comment]
The invoice can be requested from https://booking-api.skypicker.com/api/v0.1/users/self/bookings/<BID>, it is `assets.invoice` in the response.
The link to MMB webview is `https://www.kiwi.com/content/manage/<BID>/<AUTH_TOKEN>

**Comment by StanleySo** [comment]
@MRTNKCR what exactly should I reply here? You are correct with your last comment, do you need something else?

**Comment by MRTNKCR** [comment]
@StanleySo I asked you for a help well before i obtained the info above :-) If you can confirm it is correct, I believe we have everything we need here. Thanks ✌️

**Comment by StanleySo** [comment]
@MRTNKCR when you will be implementing it? 
The problem is that we are currently rewriting old mmb api to new APIs (to get rid of one huge endpoint for everything, but split it per feature/resource). 
So we can probably implement you a new mambo api endpoint for invoices - will links and all invoices info. 
It should be done in a week or two. Are you okay with it?

**Comment by mrtnzlml** [comment]
> You are correct with your last comment

I have no idea how to use `kiwi.com/content/manage/<AUTH_TOKEN>` in order to open one particular BID... 🤷‍♂️

> when you will be implementing it?

We have invoices (PDF assets) in our GraphQL for about a year now.

**Comment by mrtnzlml** [comment]
Thanks now it makes sense just for the record - this is how to open MMB (simple token - not auth):

```
https://kiwi.com/content/manage/<bid>/<simple_token>
```

And this is how to open it with deeplink:

```
https://kiwi.com/content/manage/<bid>/<simple_token>?deeplink=seating
```

All deeplinks are listed in the Dropbox Paper (with the wrong example URL though - missing simple token).

> we still prefer to move everything what possible to the new mambo endpoint. Will you be able to change it once it will be done?

Absolutely. We do not use REST API directly but we call GraphQL proxy instead. Therefore, we can change the proxy implementation without touching our clients. Everything what uses GraphQL will use the new API without even knowing it... 🎉 🙂

**Comment by StanleySo** [comment]
perfect, happy to hear it :) will keep you updated about news in mambo.
Btw several endpoints are already done, here is doc:
https://booking-api.skypicker.com/mmb/v1/ui/#/default

**Comment by mrtnzlml** [comment]
✅ Done.
