### ISSUE TITLE
Explore screen

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#528]
[Zeplin](https://zpl.io/2jZAN6r)
![image](https://cdn.zeplin.io/59a9818fe86dfd4f75f2c142/screens/814F3A27-F0BC-4332-82DE-F2C4964F1FE4.png)

## Questions
- Icons?
- There are no designs for `explore airport` should we get desing and implement it, or just navigate to the native view?

**Comment by MRTNKCR** [comment]
The icons should be taken from Fonastic - @mrtnzlml has an access.

The design for the Explore section is here https://app.zeplin.io/project/592dac0f95f16d9d5d05268f/screen/592daca6cc4244479dc69353

Please, let me know, if you miss any data/endpoints for this section.

**Comment by mrtnzlml** [comment]
@MRTNKCR Where can we find data for this screen? https://zpl.io/R29rByV

The whole explore airport is very unclear. We have only information that everything is in the `/api/v0.1/users/self/bookings/...` endpoint but that doesn't look right. We'll need way more info about this.

**Comment by tbergq** [comment]
@ferrannp this could be an issue for you, basically list out airports and destinations from the booking, and they should deeplink/navigate to existing native screen for `explore airport/city`

**Comment by MRTNKCR** [comment]
Here are the designs for Explore destination https://app.zeplin.io/project/5afaa143a602c5f1054129b9, and a basic spec https://confluence.kiwi.com/pages/viewpage.action?pageId=157617808, I'm obtaining additional info on when to display the Explore component. Once I get it, i will focus on the Explore airport feature.

**Comment by tbergq** [comment]
@MRTNKCR you said `Let's skip Explore in the RN MVP and just link the native screens.`

So we don't need all that above. We will just redirect to existing screens for now

**Comment by ferrannp** [comment]
I recommend reconsidering reimplementing this screen in RN. It does not seem as a hard one and you will do it at some point anyway. I think this will avoid the hassle to:

Native app -> RN app with react-navigation -> Native app screen ...
