### ISSUE TITLE
Contact screen

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#530]
[Zeplin](https://zpl.io/bllG1ZP)
![image](https://cdn.zeplin.io/59a9818fe86dfd4f75f2c142/screens/CC9F2A1D-AD22-4F21-935C-4C3E61B5FF19.png)

## Tasks
- [ ] Add contact
- [ ] Edit contact

## Questions
- The flow of this needs to be explained, in particular this 
![popup](https://cdn.zeplin.io/59a9818fe86dfd4f75f2c142/screens/C0703254-6A5A-4AC0-AF48-95B69577762C.png)
- What should happen when I click on each respective button
- Where do we send the data?

**Comment by MRTNKCR** [comment]
According to @vousatej, this screen is not part of the current MMB. He will delete it from zeplin and we can archive this issue. Sorry for the confusion.
