### ISSUE TITLE
Fix navigation on iOS

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#558]
## Tasks
- [x] Swipe back gesture does not work correctlly on ios(leaves entire application)
- [x] Starting rn-hotels is slow (Solved by sharing the bridge)

**Comment by pistelak** [comment]
- `Swipe back gesture does not work correctlly on ios(leaves entire application)`:

In our application we have way how to disable system swipe back gesture. You can find it `NavigationViewController` and it is method: `- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch`. If you modify this method a bit it will works BUT you have to find a way how to tell native app that user is on default screen (search screen) and system gesture should be allowed. 

I can change the method for you, but don't know to solve the second part of the problem...

**Comment by tbergq** [comment]
> you have to find a way how to tell native app that user is on default screen

There are a way to do this -> a bridge. But this means we have to activate/deactivate on the root component, which is what we do on android back button, which we really don't want to do

**Comment by pistelak** [comment]
Ok, ok. I've just wanted to point out where this code can be found in our app.  :)

**Comment by grabbou** [comment]
@pistelak thanks for pointing us out to that method. It's indeed very helpful. The problem I have with extending it is that I don't want to couple it with React Native.

The naive approach would be to just list the RNHotelsViewController in the swipeBackDisabled array of controllers. That, unfortunately, wouldn't work as you want to swipe back when there are no children inside the React Navigation hierarchy.

The best approach that I see would be to implement delegate pattern where each screen can conform to the protocol and expose method `shouldAcceptSwipeBackGesture`. That way, we can implement React Native specific logic inside the controller and your handler will just ask for it. Benefits are fewer conditionals and ability to control the swipe back gesture from within the controller itself.

Let me know what you think.

**Comment by tbergq** [comment]
@mrtnzlml what do you think about ^^

**Comment by grabbou** [comment]
Not now. The delegate approach is not a hack but standard way of doing
things.

On Android, depending on your structure, we will use the same approach.

Native team should give me an idea whether this is something they are
interested in as it touches few files on Native side.

Otherwise, we will have to do hacks here.

**Comment by tbergq** [comment]
So what does this involve from our side(JS code)

Say in the `RootComponent.componentDidMount` do something like `Bridge.allowSwipe(true)` then on other  screens `Bridge.allowSwipe(false)`?

**Comment by grabbou** [comment]
Yes. I was thinking to do it from the StackNavigation onStateChange.

We will provide you with Native Module as a PR where we can discuss the JS
API once the approach in general gets accepted.

**Comment by grabbou** [comment]
@pistelak can I have your comment on my comments above that suggest using a protocol and delegate to ask for current controller whether it should accept gestures? It involves a tiny amount of changes to the main app - we can take care of that. Details to be discussed in the appropriate PR in that repo, just trying to get a sense whether you like that idea.

**Comment by pistelak** [comment]
Hi @grabbou, 

I think, using notification is probably far better than my usage of singleton for navigation. Anyway, I'm not sure about the delegation part. You will be able to pass the information to `coordinator` but ¯\_(ツ)_/¯ - I don't know what will be the next step. 

I'd probably create `- (BOOL)isInteractivePopGestureAllowed;` (This should be probably wrapped inside of a protocol but I'm not sure where this protocol should be placed...) method in `RNKiwiViewController`. As a next step, I'd adjust the method I've mentioned earlier. 

It could look like: 

```objc
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldReceiveTouch:(UITouch *)touch {
    
    // probably not necessary 
    const BOOL kIsPopGestureRecognizer = self.interactivePopGestureRecognizer == gestureRecognizer;
    
    if (kIsPopGestureRecognizer && [self.topViewController respondsToSelector:@selector(isInteractivePopGestureAllowed)]) {
        return [(id)self.topViewController isInteractivePopGestureAllowed];
    }
}
``` 

What do you think? 

---

Oh, I did not see your previous commit earlier, so I wrote this as a reaction to existing PR... But yea, I agree with you.

**Comment by grabbou** [comment]
Yeah, that's what I am thinking right now - the part with selector could replace the hardcoded array of view controllers.

> This should be probably wrapped inside of a protocol but I'm not sure where this protocol should be placed...

Needs to be inside the mobile app I guess. We are working to implement two additional methods as a part of `RNKiwiViewControllerFlowDelegate` so that the `flowDelegate` (in your case, `RNHotelsFlowViewController`) can obtain an information whether to accept gestures or not.

Once it has this information (e.g. as a boolean property), it can return it from the `isInteractivePopGestureAllowed` method that it implements as a part of native-app specific protocol.

Seems right :)

**Comment by ferrannp** [comment]
@tbergq I made this issue only iOS related. Can you explain the step ` We have to call bridge module to leave application` ?

**Comment by ferrannp** [comment]
Ok I'll move it to Android specific issue and investigate it.

**Comment by ferrannp** [comment]
Now that https://github.com/kiwicom/mobile/pull/623 is merged, `ios` native app needs to use it in order to fix the swipe back gesture.

**Comment by tbergq** [comment]
@pistelak ^^

**Comment by grabbou** [comment]
We have open issue to decide how to integrate this with mobile app - either we do protocol-based communication, or, we employ some hardcoded hacks based on `flowDelegate`.

**Comment by mrtnzlml** [comment]
Resolved? Can we close it? 🙂

**Comment by ferrannp** [comment]
Solved.
