### ISSUE TITLE
MMB: Offline availability

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#601]
The current MMB seems to work offline. 

Should we implement this, how should we handel it?

Possible solutions:
• Cache the data in `PrivateApiRenderer` and serve data from there if offline
• Create a context and store the context to device

**Comment by mrtnzlml** [comment]
I would start with the query renderer (maybe even public one). Let's store the latest response and use it only when offline. It's tricky because `NetInfo` [is broken](https://github.com/facebook/react-native/issues/8615) but this may be fixed very soon.

However, we should be really careful with the cache because GraphQL caching [is complicated](https://graphql.org/learn/caching/). We should probably find an existing solution.

**Comment by tbergq** [comment]
It is hard to find existing solutions. I found this:

https://github.com/facebook/relay/issues/2043

So it seems we are not the only ones wanting this

**Comment by mrtnzlml** [comment]
Ignore that - that's not that complicated. I already implemented it once. We are looking for generic GraphQL response cache (because you cannot just simply store the JSON)...

**Comment by tbergq** [comment]
@mrtnzlml Can this be closed now? ref #745

**Comment by mrtnzlml** [comment]
Not yet. We don't have proper offline support yet.

**Comment by tbergq** [comment]
What is missing for this issue to be closed?

**Comment by mrtnzlml** [comment]
Offline support... 😄

#745 is more like a Relay store cache. This way we don't have to fetch it from the API but we can just restore the previous snapshot. But we are always sending requests to the network (this should be improved) and we also have to test how does the app behave while offline only without the cache restored (the #745 is really solving something little bit different).

Also, it's not that easy. We don't have some kind of sync so we should disalow mutations while offline (app should be basically only read-only).

**Comment by tbergq** [comment]
We no longer call api when we do not have connection. Still we need to prefetch all data in MMB to have full offline support. Now we only have offline support for previously visited screens. 

When https://github.com/facebook/relay/pull/2354 has been merged, we should be able to prefetch as well.

**Comment by mrtnzlml** [comment]
@tbergq Do you need it ASAP or do we still have time for it?

**Comment by tbergq** [comment]
Closing, we should create new issues if we ever touch MMB again
