### ISSUE TITLE
CircleCI automation

### ISSUE THREAD

**Issue by grabbou** [kiwicom/mobile#620]
Once #610 lands into master, let's work on making CircleCI do the release automatically every time the tests pass on master.

To do so, I believe we just need to run `yarn release` on CI with appropriate environmental settings.

- [x] Need to run 2 jobs (build and if it is green, then release). Only on `master`
- [x] Needs to set up signing iOS code

**Comment by ferrannp** [comment]
Done!

**Comment by mrtnzlml** [comment]
Awesome! So can you please send me "how to" guide so I can update the docs?
