### ISSUE TITLE
Check Navigation on Android

### ISSUE THREAD

**Issue by ferrannp** [kiwicom/mobile#632]
- [x] We have to call bridge module to leave application
- [x] We have to use `WithBackButtonListener` HOC for android back button to work correctly

For the first one, right now:

```js
onBackClicked = () => {
    if (NativeModules.RNNavigationModule) {
      NativeModules.RNNavigationModule.leaveHotels();
    } else {
      this.props.onBackClicked();
    }
  };
```

This issues is to investigate alternative ways to do this or decide if this is the best way.

**Comment by mrtnzlml** [comment]
Resolved? Can we close it? 🙂

**Comment by ferrannp** [comment]
Solved.
