### ISSUE TITLE
RN Distribution on Android

### ISSUE THREAD

**Issue by ferrannp** [kiwicom/mobile#634]
- [x] Move https://gitlab.skypicker.com/mobile/react-native-hotels/ here
- [x] Move https://gitlab.skypicker.com/mobile/react-native-native-modules/tree/master/android here
- [x] Credentials to deploy are hardcoded in the private repo, they cannot be here
- [x] Create playground for Android (to test the app in this repo)

**Benefits**

- No more npm releases
- All in one package, no need to warn about updates like new `react-native` version
- Be able to have a playground to test it
- CircleCI could automate things for us

cc @grabbou @lukewalczak @tbergq @mrtnzlml 

This issue is to discuss what we want to do with Android distribution. Radek Barton should probably be part of it too.

**Comment by mrtnzlml** [comment]
cc @Blackhex

**Comment by Blackhex** [comment]
Seems fine for us so far.

The credentials will be removed even from the private repo and distributed via 1Password until we find a way how to store them securely while obtain them automatically.

But what is meant by "playground for Android" exactly?

**Comment by grabbou** [comment]
It's a demo app within this repository where we can test stuff and also,
demonstrate the integration with the Android module. That way, we do not
have to constantly work on your native repository to test things out and we
give you a nice public overview of the API.

**Comment by ferrannp** [comment]
I'll create an issue with a second part.
