### ISSUE TITLE
RFC: separate apps and packages

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/mobile#642]
I propose the following directory structure:

```
.
├── app/
│   ├── core/        - ???
│   ├── hotels/
│   └── MMB/
└── packages/
    ├── accessibility/
    ├── localization/
    ├── navigation/
    |    ...
    └── shared/
```

Directory `app/` would contain only the independent applications and `packages/` would be the true Yarn workspaces. Currently, we are mixing it together (our apps are not workspaces).

cc @tbergq

**Comment by tbergq** [comment]
Yes, that sounds like a good idea
