### ISSUE TITLE
Create trip timeline

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/mobile#687]
See: https://docs.google.com/document/d/1Y1kQcoTBl-laxMXbkQRA5v3yuWU_ydZjAvj78WwXq_4/edit

There is also tablet layout:

![screen shot 2018-05-31 at 14 44 33](https://user-images.githubusercontent.com/978368/40782933-2ee7b48c-64e1-11e8-8631-28458fe917b1.png)

https://zpl.io/bew7lZD

**Comment by RobinCsl** [comment]
- [x] MVP: BookedFlightTimelineEvent & AirportArrivalTimelineEvent
- [ ] Display Day banner only once for each day involved in the timeline and not for every event of the timeline
- [ ] LeaveForAirportTimelineEvent
- [ ] DownloadReceiptTimelineEvent
- [ ] DownloadETicketTimelineEvent
- [ ] BoardingTimelineEvent
- [ ] DepartureTimelineEvent
- [ ] ArrivalTimelineEvent
- [ ] TransportFromAirportTimelineEvent

**Comment by RobinCsl** [comment]
Additional Tasks:
- [] Refactor DownloadEventIcon to have boolean props about displaying top line/displaying the bottom line or not; (currently props isFirst)
- [] Apply correct font color to past events
- [] Add the location to the DateLocation component
- [] DateLocation font color should be red if AirportArrival or Arrival timeline events

**Comment by RobinCsl** [comment]
Additional Tasks:
- [x] Add DownloadBoardingPass event

**Comment by tbergq** [comment]
Closing, we should create new issues if we ever touch MMB again
