### ISSUE TITLE
Hotels: unnecessary re-rendering with the context change

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/mobile#735]
The hotel page is re-rendering with every hotel's context change (for example after setting the filter). This means that the UI feels weird (it's actually a bug) and more importantly some parts don't work correctly (setting filter - this component is rerendered and therefore the `scrollTo` to start doesn't work correctly)...

**Comment by tbergq** [comment]
This still is an issue, but does not create any side effects.
