### ISSUE TITLE
GetDeviceLocale.js may return unexpected values

### ISSUE THREAD

**Issue by mrtnzlml** [kiwicom/mobile#738]
For example this: `"es_SA@calendar=gregorian"`. We do not expect this and we should refactor it ASAP...

**Comment by tbergq** [comment]
Does this happen for iOS and/or Android?

**Comment by mrtnzlml** [comment]
I think this is from my iOS device.

**Comment by tbergq** [comment]
Interesting, I just tested from my device, and I get, en-GB as expected.

@ferrannp you have some experience with this?

**Comment by mrtnzlml** [comment]
@tbergq It's not that hard to set it - just use for example Arabic language for the device in Europe (very common in Germany for example)...

**Comment by tbergq** [comment]
That gave me ar-ES
