### ISSUE TITLE
Close button on detail screen doesn't work

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#945]
[Trello](https://trello.com/c/ayHkH1TC/307-bug-close-button-on-detail-screen-doesnt-work)

**Comment by ferrannp** [comment]
I cannot reproduce it. It works for me in the native playground. How are you using it?

**Comment by tbergq** [comment]
@pistelak did you try with latest version?

**Comment by ferrannp** [comment]
I think it is related to #950. Nothing is clickable till some time passes.

**Comment by ferrannp** [comment]
Ok I saw the issue with the Slack video.
