### ISSUE TITLE
Transportation - Trip Services

### ISSUE THREAD

**Issue by tbergq** [kiwicom/mobile#987]
[Docs](https://confluence.kiwi.com/display/MOB/Transportation)

**Comment by MRTNKCR** [comment]
Here is the screen flow:

![img_2042](https://user-images.githubusercontent.com/7661448/44085317-6f8d358a-9fb9-11e8-84b5-cc99d760656d.PNG)
 
![img_2043](https://user-images.githubusercontent.com/7661448/44085316-6f596958-9fb9-11e8-92a3-229e8fc948b8.PNG)
 
![img_2044](https://user-images.githubusercontent.com/7661448/44085314-6f354faa-9fb9-11e8-917d-f06a96c7f810.PNG)
 
![img_2045](https://user-images.githubusercontent.com/7661448/44085313-6f11ae1a-9fb9-11e8-9903-68a81dcfb8ac.PNG)
 
![img_2046](https://user-images.githubusercontent.com/7661448/44085312-6eebc07e-9fb9-11e8-8bc4-e1b0b760f2c9.PNG)

**Comment by lukewalczak** [comment]
- [ ] - connect grapql data
- [ ] - map view
- [ ] - web view

**Comment by RobinCsl** [comment]
- [ ] Search for addresses in address picker screen PR #1093 
- [ ] Display searched addresses PR #1094 
- [ ] Display recent searches

**Comment by tbergq** [comment]
Closing, we should create new issues if we ever touch MMB again
